categorical_features:
  - CO_MUN_NOT
  - COD_IDADE
  - RAIOX_OUT
  - CO_REGIONA
  - SG_UF_NOT
  - CS_SEXO
  - CS_GESTANT
  - CS_RACA
  - CS_ESCOL_N
  - SG_UF
  - CS_ZONA
  - SURTO_SG
  - NOSOCOMIAL
  - AVE_SUINO
  - FEBRE
  - TOSSE
  - GARGANTA
  - DISPNEIA
  - DESC_RESP
  - SATURACAO
  - DIARREIA
  - VOMITO
  - OUTRO_SIN
  - PUERPERA
  - FATOR_RISC
  - CARDIOPATI
  - HEMATOLOGI
  - SIND_DOWN
  - HEPATICA
  - ASMA
  - DIABETES
  - NEUROLOGIC
  - PNEUMOPATI
  - IMUNODEPRE
  - RENAL
  - OBESIDADE
  - OUT_MORBI
  - VACINA
  - ANTIVIRAL
  - TP_ANTIVIR
  - HOSPITAL
  - UTI
  - SUPORT_VEN
  - RAIOX_RES
  - AMOSTRA
  - TP_AMOSTRA
  - HISTO_VGM
  - DOR_ABD
  - FADIGA
  - PERD_OLFT
  - PERD_PALA
  - TOMO_RES
  - VACINA_COV
  - DOSE_1_COV
  - DOSE_2_COV
  - FNT_IN_COV
  - regiao

numerical_features:
  - SEM_NOT
  - SEM_PRI
  - NU_IDADE_N
  - latitude_m
  - longitude_m
  - pib

target_column:
  - CLASSI_FIN
