columns_to_keep:
  - CS_SEXO
  - NU_IDADE_N
  - CS_GESTANT
  - NOSOCOMIAL
  - AVE_SUINO
  - FEBRE
  - TOSSE
  - GARGANTA
  - DISPNEIA
  - DESC_RESP
  - SATURACAO
  - OUTRO_SIN
  - FATOR_RISC
  - VACINA
  - ANTIVIRAL
  - HOSPITAL
  - UTI
  - SUPORT_VEN
  - FADIGA
  # merece juntar
  - VACINA_COV
  - DOSE_2_COV
  - DOSE_1_COV
  # ...
  - FNT_IN_COV
  - VOMITO
  - DIARREIA
  - PERD_OLFT
  - DOR_ABD
  - PERD_PALA
  - SIND_DOWN
  - HEMATOLOGI
  - IMUNODEPRE
  - DIABETES
  - ASMA
  - RENAL
  - CARDIOPATI
  - TOMO_RES
  - RAIOX_RES
  - OUT_MORBI
  - OBESIDADE
  - NEUROLOGIC
  - PNEUMOPATI
  - PUERPERA
  - TP_ANTIVIR
  - MAE_VAC

columns_to_drop:
  - OBES_IMC
  - TOMO_OUT
  - MORB_DESC
  - RAIOX_OUT
  - OUTRO_DES
  - DOSE_REF # quasi zero variance
  - DELTA_UTI # zero variance
  - HEPATICA
  - PAC_COCBO
  - AMOSTRA
  - CO_REGIONA
  - CS_ZONA
  - HISTO_VGM
  - SG_UF
  - SEM_NOT
  - OUT_AMOST
  - SURTO_SG
  - CO_MUN_NOT
  - SEM_PRI
  - ID_MUNICIP
  - PAC_DSCBO
  - OUT_ANIM
  - ID_REGIONA
  - COD_IDADE
  - CS_ESCOL_N
  - TP_IDADE
  - M_AMAMENTA
  - TP_AMOSTRA
  - CS_RACA
  - SG_UF_NOT

high_cardinality_features:

categorical_features:
  - CO_MUN_NOT
  - CO_REGIONA
  - SG_UF_NOT
  # - ID_REGIONA
  # - ID_MUNICIP
  - CS_SEXO
  - COD_IDADE
  - CS_GESTANT
  - CS_RACA
  - CS_ESCOL_N
  - SG_UF
  - CS_ZONA
  - SURTO_SG
  - NOSOCOMIAL
  - AVE_SUINO
  - FEBRE
  - TOSSE
  - GARGANTA
  - DISPNEIA
  - DESC_RESP
  - SATURACAO
  - DIARREIA
  - VOMITO
  - OUTRO_SIN
  # - OUTRO_DES
  - PUERPERA
  - FATOR_RISC
  - CARDIOPATI
  - HEMATOLOGI
  - SIND_DOWN
  - HEPATICA
  - ASMA
  - DIABETES
  - NEUROLOGIC
  - PNEUMOPATI
  - IMUNODEPRE
  - RENAL
  - OBESIDADE
  - OUT_MORBI
  # - MORB_DESC
  - VACINA
  # - MAE_VAC
  # - M_AMAMENTA
  - ANTIVIRAL
  # - TP_ANTIVIR
  - HOSPITAL
  - UTI
  - SUPORT_VEN
  - RAIOX_RES
  - RAIOX_OUT
  - AMOSTRA
  - TP_AMOSTRA
  # - OUT_AMOST
  - HISTO_VGM
  # - PAC_COCBO
  # - PAC_DSCBO
  # - OUT_ANIM
  - DOR_ABD
  - FADIGA
  - PERD_OLFT
  - PERD_PALA
  - TOMO_RES
  # - TOMO_OUT
  - VACINA_COV
  - DOSE_1_COV
  - DOSE_2_COV
  - FNT_IN_COV
  # - TP_IDADE
  # - capital
  - regiao

categorical_features_order_matters:

numerical_features:
  # - OBES_IMC
  - SEM_NOT
  - SEM_PRI
  - NU_IDADE_N
  # - RISCK_FACTORS
  # - SINTOMAS_FACTORS
  - latitude_m
  - longitude_m
  # - latitude_e
  # - longitude_e
  

target_column:
  - CLASSI_FIN

# map_variables:
#   - CO_MUN_NOT: municipio_code_ibge
#   - CO_REGIONA: regionais_saude_code_ibge
#   - SG_UF_NOT: 
#   # - ID_REGIONA
#   # - ID_MUNICIP
#   - CS_SEXO
#   - COD_IDADE
#   - CS_GESTANT
#   - CS_RACA
#   - CS_ESCOL_N
#   - SG_UF
#   - CS_ZONA
#   - SURTO_SG
#   - NOSOCOMIAL
#   - AVE_SUINO
#   - FEBRE
#   - TOSSE
#   - GARGANTA
#   - DISPNEIA
#   - DESC_RESP
#   - SATURACAO
#   - DIARREIA
#   - VOMITO
#   - OUTRO_SIN
#   # - OUTRO_DES
#   - PUERPERA
#   - FATOR_RISC
#   - CARDIOPATI
#   - HEMATOLOGI
#   - SIND_DOWN
#   - HEPATICA
#   - ASMA
#   - DIABETES
#   - NEUROLOGIC
#   - PNEUMOPATI
#   - IMUNODEPRE
#   - RENAL
#   - OBESIDADE
#   - OUT_MORBI
#   # - MORB_DESC
#   - VACINA
#   # - MAE_VAC
#   # - M_AMAMENTA
#   - ANTIVIRAL
#   # - TP_ANTIVIR
#   - HOSPITAL
#   - UTI
#   - SUPORT_VEN
#   - RAIOX_RES
#   - RAIOX_OUT
#   - AMOSTRA
#   - TP_AMOSTRA
#   # - OUT_AMOST
#   - HISTO_VGM
#   # - PAC_COCBO
#   # - PAC_DSCBO
#   # - OUT_ANIM
#   - DOR_ABD
#   - FADIGA
#   - PERD_OLFT
#   - PERD_PALA
#   - TOMO_RES
#   # - TOMO_OUT
#   - VACINA_COV
#   - DOSE_1_COV
#   - DOSE_2_COV
#   - FNT_IN_COV
#   # - TP_IDADE
#   # - OBES_IMC
#   - SEM_NOT
#   - SEM_PRI
#   - NU_IDADE_N
#   - CLASSI_FIN


# dados_paciente:


# dados_residencia:


# dados_clinicos:


# dados_atendimentos:

# dados_laboratoriais:


